import { Inter } from 'next/font/google';
import TopHeader from './layout_components/topHeader';
import NavBar from './layout_components/navbar';
import { motion,useScroll  } from 'framer-motion';
const inter = Inter({ subsets: ['latin'] })
import Loading from './components/loading';
import React, { useEffect, useState } from 'react';
import FloatingBlocks from './layout_components/FloatingBlocks';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function LoadingPage() {
  return <Loading />
}
function MainPage(props){
  const { scrollYProgress } = useScroll();
  return (
    <div>
      <motion.div style={{ scaleX: scrollYProgress }} className='scroll-progress-bar' />
      <TopHeader />
      <NavBar />
      <FloatingBlocks />
      <main>
        {props.children}
      </main>
    </div>
  )
}
export default class RootLayout extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      loading: true,
      children: props,
    }
  }
  componentDidMount () {
    this.setState({
      loading: false,
    })
  }
  render () {
    if(this.state.loading){
      return (
        <LoadingPage />
      )
    } else {
      return (
        <MainPage children={this.props.children} />
      )
    }
  }
}
