import { Inter } from 'next/font/google';
import TopHeader from './layout_components/topHeader';
import NavBar from './layout_components/navbar';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <div>
      <TopHeader />
      <NavBar />
      
      <div class="area" >
        <ul class="circles">
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
        </ul>
      </div>
      <main>
        {children}
      </main>
    </div>
  )
}
